%DefaultEncoding "UTF-8"

namespace Pyro {
%TypeHeaderCode
#include <pyro/pyroconstants.h>
%End
    const double PI;
    const double TWO_PI;
    const double HALF_PI;
    const double QUARTER_PI;

    const int OPEN;
    const int CLOSE;

    // Arc drawing styles
    const int PIE;
    const int CHORD;
    
    // Stroke caps
    const int ROUND;
    const int SQUARE;
    const int PROJECT;

    const int HSB;
    const int HSBA;
    const int RGB;
    const int RGBA;
};