name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-22.04-gcc-12, macos-13-xcode]

        include:
          - name: ubuntu-22.04-gcc-12
            os: ubuntu-22.04
            version: "12"

          - name: macos-13-xcode
            os: macos-13
            version: "13"

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: "true"
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update

          sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
          echo "name=CC::gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "name=CXX::g++-${{ matrix.version }}" >> $GITHUB_ENV 

          sudo apt-get install libsdl2-dev libpng-dev git-lfs libjpeg-turbo8-dev libeigen3-dev
          pip install meson ninja

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pip3 install meson ninja
          brew install freetype libjpeg-turbo cairo libpng sdl2 pkg-config eigen

          # ls -ls /Applications/
          # sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
      - name: Build project
        run: |
          meson setup build
          ninja -C build
      - name: Run tests
        run: |
          ninja -C build test

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots-${{ matrix.name}}
          path: ./screenshots
